apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-container
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "MySuperSecret"
        - name: MYSQL_DATABASE
          value: "testdb"
        ports:
        - containerPort: 3306
