apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: rabbitmq-container
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672  # AMQP
        - containerPort: 15672 # Management UI
