apiVersion: v1
kind: Service
metadata:
  name: queue-service
spec:
  selector:
    app: queue
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: mgmt
      port: 15672
      targetPort: 15672
